/**
 * Converts an LDtk project into the compact, engine-facing level shape
 * consumed by @mmx/engine's LevelData, and emits it as a TypeScript module
 * source.
 *
 * Why a build step rather than loading .ldtk at runtime: an LDtk file is large
 * (editor state, defs, auto-layer rules) and its schema moves between
 * versions. Keeping the parse here means the engine never sees any of that,
 * and the same generated module is consumed identically by Vite, tsc and the
 * tsx sim — a runtime `import ... from './x.ldtk'` would need
 * bundler-specific handling.
 *
 * Emitting .ts rather than .json is deliberate for the same reason: JSON
 * modules need import attributes in Node ESM, and support differs across the
 * three toolchains this project builds with.
 */
import { applySlopes, slopeRects, type LevelEntityLike, type SlopeMap } from "./slopeBake.js";
import type { LdtkEntityInstance, LdtkProject } from "./ldtkTypes.js";

/** IntGrid value -> Tile enum member name. Mirrors Tile in the engine's World.ts. */
const VALUE_TO_TILE: Record<number, string> = {
  0: "Empty",
  1: "Solid",
  2: "SlopeUpRight",
  3: "SlopeUpLeft",
};

export interface ConvertedLevel {
  identifier: string;
  gridSize: number;
  cols: number;
  rows: number;
  tiles: string[];
  slopes: SlopeMap;
  entities: LevelEntityLike[];
}

export function convert(ldtk: LdtkProject, sourceName: string): ConvertedLevel {
  const level = ldtk.levels?.[0];
  if (!level) throw new Error(`${sourceName}: no levels`);
  if (level.externalRelPath) {
    throw new Error(
      `${sourceName}: uses external level files; turn off "Save levels to separate files" in LDtk project settings`,
    );
  }

  const layers = level.layerInstances ?? [];
  const collision = layers.find((l) => l.__type === "IntGrid");
  if (!collision) throw new Error(`${sourceName}: no IntGrid layer`);

  const cols = collision.__cWid;
  const rows = collision.__cHei;
  const csv = collision.intGridCsv;
  if (csv.length !== cols * rows) {
    throw new Error(`${sourceName}: intGridCsv is ${csv.length}, expected ${cols * rows}`);
  }

  const tiles = csv.map((v) => {
    const name = VALUE_TO_TILE[v];
    if (name === undefined) {
      throw new Error(
        `${sourceName}: IntGrid value ${v} has no Tile mapping; add it to VALUE_TO_TILE and the Tile enum`,
      );
    }
    return name;
  });

  const entityInstances: LdtkEntityInstance[] = layers
    .filter((l) => l.__type === "Entities")
    .flatMap((l) => l.entityInstances ?? []);

  // The engine reads entity boxes as top-left + size, so a non-zero pivot would
  // silently shift every zone and spawn. Caught here rather than debugged later
  // as a camera that stops half a screen short of where the rectangle was drawn.
  for (const e of entityInstances) {
    const [px, py] = e.__pivot ?? [0, 0];
    if (px !== 0 || py !== 0) {
      throw new Error(
        `${sourceName}: entity '${e.__identifier}' pivots at ${px},${py}; set its pivot to top-left (0,0) in LDtk`,
      );
    }
  }

  const entities: LevelEntityLike[] = entityInstances.map((e) => ({
    id: e.__identifier,
    iid: e.iid,
    // px is pivot-adjusted; every entity def here pivots at 0,0, so this is
    // the box's top-left and `width`/`height` extend right/down from it.
    x: e.px[0],
    y: e.px[1],
    w: e.width,
    h: e.height,
    fields: Object.fromEntries((e.fieldInstances ?? []).map((f) => [f.__identifier, f.__value])),
  }));

  // Ramps last: a Slope box owns the tiles under it and overwrites whatever the
  // IntGrid had there, so a designer shapes a hill by dragging the box rather
  // than also keeping a painted staircase in step with it.
  const slopes = applySlopes(tiles, cols, slopeRects(entities), sourceName);

  return {
    identifier: level.identifier,
    gridSize: collision.__gridSize,
    cols,
    rows,
    tiles,
    slopes,
    entities,
  };
}

/** Emit the tile grid one row per line so diffs on a level edit stay readable. */
function formatTiles(tiles: string[], cols: number): string {
  const lines: string[] = [];
  for (let y = 0; y < tiles.length / cols; y++) {
    const row = tiles.slice(y * cols, (y + 1) * cols);
    lines.push("  " + row.map((t) => `T.${t}`).join(", ") + ",");
  }
  return lines.join("\n");
}

/**
 * Emit the baked slope profiles one per line, annotated with the grid position
 * the index stands for — the index alone is unreadable in a review, and this is
 * the one part of a generated level a human ever has cause to check by eye.
 */
function formatSlopes(slopes: SlopeMap, cols: number): string {
  const entries = Object.entries(slopes);
  if (entries.length === 0) return "";
  const lines = entries.map(([index, [l, r]]) => {
    const i = Number(index);
    return `    ${i}: [${l}, ${r}], // ${i % cols},${Math.floor(i / cols)}`;
  });
  return `  slopes: {\n${lines.join("\n")}\n  },\n`;
}

export function emit(level: ConvertedLevel, sourceName: string): string {
  return `// Generated by @mmx/ldtk-tools (pnpm level:import) from levels/${sourceName} — do not edit.
// Edit the .ldtk file in LDtk, then run \`pnpm level:import\`.
import { Tile as T } from '../World.js';
import type { LevelData } from '../LevelData.js';

export const level: LevelData = {
  identifier: ${JSON.stringify(level.identifier)},
  gridSize: ${level.gridSize},
  cols: ${level.cols},
  rows: ${level.rows},
  entities: ${JSON.stringify(level.entities)},
${formatSlopes(level.slopes, level.cols)}  tiles: [
${formatTiles(level.tiles, level.cols)}
  ],
};
`;
}
