packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - electron-ipc-module
  - rollup-plugin-electron-run
  - "@parcel/watcher"
  - esbuild

patchedDependencies:
  electron-ipc-module@0.1.0: patches/electron-ipc-module@0.1.0.patch
