import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkgRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(pkgRoot, "../../resources/sprites");
const target = join(pkgRoot, "assets/sprites");

rmSync(target, { recursive: true, force: true });
mkdirSync(dirname(target), { recursive: true });
cpSync(source, target, { recursive: true });

const jsonExports = [
  ["sprites/player/x_anims.json", "animData"],
  ["sprites/effects/shot_anims.json", "shotAnims"],
  ["sprites/enemies/enemy_anims.json", "enemyAnims"],
  ["sprites/pickups/pickup_anims.json", "pickupAnims"],
];

const lines = [
  "// Generated by scripts/sync-assets.mjs — do not edit.",
  "",
];

for (const [relativePath, exportName] of jsonExports) {
  const raw = readFileSync(join(pkgRoot, "assets", relativePath), "utf8");
  JSON.parse(raw);
  lines.push(`export const ${exportName} = ${raw};`);
  lines.push("");
}

writeFileSync(join(pkgRoot, "src/render/generatedAssetJson.ts"), `${lines.join("\n")}\n`);
