/**
 * Converts LDtk project files in levels/ into compact TypeScript modules under
 * src/engine/levels/.
 *
 *   node tools/import-ldtk.mjs        # or: npm run level:import
 *
 * Why a build step rather than loading .ldtk at runtime: an LDtk file is large
 * (editor state, defs, auto-layer rules) and its schema moves between versions.
 * Keeping the parse here means the engine never sees any of that, and the same
 * generated module is consumed identically by Vite, tsc and the tsx sim — a
 * runtime `import ... from './x.ldtk'` would need bundler-specific handling.
 *
 * Emitting .ts rather than .json is deliberate for the same reason: JSON modules
 * need import attributes in Node ESM, and support differs across the three
 * toolchains this project builds with.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { basename } from 'node:path';

const SRC_DIR = new URL('../levels/', import.meta.url);
const OUT_DIR = new URL('../src/engine/levels/', import.meta.url);

/** IntGrid value -> Tile enum member name. Mirrors Tile in src/engine/World.ts. */
const VALUE_TO_TILE = { 0: 'Empty', 1: 'Solid', 2: 'SlopeUpRight', 3: 'SlopeUpLeft' };

function convert(ldtk, sourceName) {
  const level = ldtk.levels?.[0];
  if (!level) throw new Error(`${sourceName}: no levels`);
  if (level.externalRelPath) {
    throw new Error(
      `${sourceName}: uses external level files; turn off "Save levels to separate files" in LDtk project settings`,
    );
  }

  const layers = level.layerInstances ?? [];
  const collision = layers.find((l) => l.__type === 'IntGrid');
  if (!collision) throw new Error(`${sourceName}: no IntGrid layer`);

  const cols = collision.__cWid;
  const rows = collision.__cHei;
  const csv = collision.intGridCsv;
  if (csv.length !== cols * rows) {
    throw new Error(`${sourceName}: intGridCsv is ${csv.length}, expected ${cols * rows}`);
  }

  const tiles = csv.map((v) => {
    const name = VALUE_TO_TILE[v];
    if (name === undefined) {
      throw new Error(
        `${sourceName}: IntGrid value ${v} has no Tile mapping; add it to VALUE_TO_TILE and the Tile enum`,
      );
    }
    return name;
  });

  const entities = layers
    .filter((l) => l.__type === 'Entities')
    .flatMap((l) => l.entityInstances ?? [])
    .map((e) => ({
      id: e.__identifier,
      x: e.px[0],
      y: e.px[1],
      fields: Object.fromEntries(
        (e.fieldInstances ?? []).map((f) => [f.__identifier, f.__value]),
      ),
    }));

  return { identifier: level.identifier, gridSize: collision.__gridSize, cols, rows, tiles, entities };
}

/** Emit the tile grid one row per line so diffs on a level edit stay readable. */
function formatTiles(tiles, cols) {
  const lines = [];
  for (let y = 0; y < tiles.length / cols; y++) {
    const row = tiles.slice(y * cols, (y + 1) * cols);
    lines.push('  ' + row.map((t) => `T.${t}`).join(', ') + ',');
  }
  return lines.join('\n');
}

function emit(level, sourceName) {
  return `// Generated by tools/import-ldtk.mjs from levels/${sourceName} — do not edit.
// Edit the .ldtk file in LDtk, then run \`npm run level:import\`.
import { Tile as T } from '../World.js';
import type { LevelData } from '../LevelData.js';

export const level: LevelData = {
  identifier: ${JSON.stringify(level.identifier)},
  gridSize: ${level.gridSize},
  cols: ${level.cols},
  rows: ${level.rows},
  entities: ${JSON.stringify(level.entities)},
  tiles: [
${formatTiles(level.tiles, level.cols)}
  ],
};
`;
}

mkdirSync(OUT_DIR, { recursive: true });

const sources = readdirSync(SRC_DIR).filter((f) => f.endsWith('.ldtk'));
if (sources.length === 0) {
  console.error('no .ldtk files in levels/');
  process.exit(1);
}

for (const source of sources) {
  const ldtk = JSON.parse(readFileSync(new URL(source, SRC_DIR), 'utf8'));
  const level = convert(ldtk, source);
  const name = basename(source, '.ldtk');
  writeFileSync(new URL(`${name}.ts`, OUT_DIR), emit(level, source));
  console.log(
    `${source} -> src/engine/levels/${name}.ts (${level.cols}x${level.rows}, ${level.entities.length} entities)`,
  );
}
