/**
 * Converts LDtk project files in levels/ into compact TypeScript modules under
 * packages/engine/src/engine/levels/.
 *
 *   node tools/import-ldtk.mjs        # or: pnpm level:import
 *
 * Why a build step rather than loading .ldtk at runtime: an LDtk file is large
 * (editor state, defs, auto-layer rules) and its schema moves between versions.
 * Keeping the parse here means the engine never sees any of that, and the same
 * generated module is consumed identically by Vite, tsc and the tsx sim — a
 * runtime `import ... from './x.ldtk'` would need bundler-specific handling.
 *
 * Emitting .ts rather than .json is deliberate for the same reason: JSON modules
 * need import attributes in Node ESM, and support differs across the three
 * toolchains this project builds with.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { basename } from "node:path";
import { applySlopes, slopeRects } from "./slope-bake.mjs";

const SRC_DIR = new URL("../levels/", import.meta.url);
const OUT_DIR = new URL("../packages/engine/src/engine/levels/", import.meta.url);

/** IntGrid value -> Tile enum member name. Mirrors Tile in the engine's World.ts. */
const VALUE_TO_TILE = { 0: "Empty", 1: "Solid", 2: "SlopeUpRight", 3: "SlopeUpLeft" };

function convert(ldtk, sourceName) {
  const level = ldtk.levels?.[0];
  if (!level) throw new Error(`${sourceName}: no levels`);
  if (level.externalRelPath) {
    throw new Error(
      `${sourceName}: uses external level files; turn off "Save levels to separate files" in LDtk project settings`,
    );
  }

  const layers = level.layerInstances ?? [];
  const collision = layers.find((l) => l.__type === "IntGrid");
  if (!collision) throw new Error(`${sourceName}: no IntGrid layer`);

  const cols = collision.__cWid;
  const rows = collision.__cHei;
  const csv = collision.intGridCsv;
  if (csv.length !== cols * rows) {
    throw new Error(`${sourceName}: intGridCsv is ${csv.length}, expected ${cols * rows}`);
  }

  const tiles = csv.map((v) => {
    const name = VALUE_TO_TILE[v];
    if (name === undefined) {
      throw new Error(
        `${sourceName}: IntGrid value ${v} has no Tile mapping; add it to VALUE_TO_TILE and the Tile enum`,
      );
    }
    return name;
  });

  const entityInstances = layers
    .filter((l) => l.__type === "Entities")
    .flatMap((l) => l.entityInstances ?? []);

  // The engine reads entity boxes as top-left + size, so a non-zero pivot would
  // silently shift every zone and spawn. Caught here rather than debugged later
  // as a camera that stops half a screen short of where the rectangle was drawn.
  for (const e of entityInstances) {
    const [px, py] = e.__pivot ?? [0, 0];
    if (px !== 0 || py !== 0) {
      throw new Error(
        `${sourceName}: entity '${e.__identifier}' pivots at ${px},${py}; set its pivot to top-left (0,0) in LDtk`,
      );
    }
  }

  const entities = entityInstances.map((e) => ({
    id: e.__identifier,
    // px is pivot-adjusted; every entity def here pivots at 0,0, so this is
    // the box's top-left and `width`/`height` extend right/down from it.
    x: e.px[0],
    y: e.px[1],
    w: e.width,
    h: e.height,
    fields: Object.fromEntries((e.fieldInstances ?? []).map((f) => [f.__identifier, f.__value])),
  }));

  // Ramps last: a Slope box owns the tiles under it and overwrites whatever the
  // IntGrid had there, so a designer shapes a hill by dragging the box rather
  // than also keeping a painted staircase in step with it.
  const slopes = applySlopes(tiles, cols, slopeRects(entities), sourceName);

  return {
    identifier: level.identifier,
    gridSize: collision.__gridSize,
    cols,
    rows,
    tiles,
    slopes,
    entities,
  };
}

/** Emit the tile grid one row per line so diffs on a level edit stay readable. */
function formatTiles(tiles, cols) {
  const lines = [];
  for (let y = 0; y < tiles.length / cols; y++) {
    const row = tiles.slice(y * cols, (y + 1) * cols);
    lines.push("  " + row.map((t) => `T.${t}`).join(", ") + ",");
  }
  return lines.join("\n");
}

/**
 * Emit the baked slope profiles one per line, annotated with the grid position
 * the index stands for — the index alone is unreadable in a review, and this is
 * the one part of a generated level a human ever has cause to check by eye.
 */
function formatSlopes(slopes, cols) {
  const entries = Object.entries(slopes);
  if (entries.length === 0) return "";
  const lines = entries.map(([index, [l, r]]) => {
    const i = Number(index);
    return `    ${i}: [${l}, ${r}], // ${i % cols},${Math.floor(i / cols)}`;
  });
  return `  slopes: {\n${lines.join("\n")}\n  },\n`;
}

function emit(level, sourceName) {
  return `// Generated by tools/import-ldtk.mjs from levels/${sourceName} — do not edit.
// Edit the .ldtk file in LDtk, then run \`pnpm level:import\`.
import { Tile as T } from '../World.js';
import type { LevelData } from '../LevelData.js';

export const level: LevelData = {
  identifier: ${JSON.stringify(level.identifier)},
  gridSize: ${level.gridSize},
  cols: ${level.cols},
  rows: ${level.rows},
  entities: ${JSON.stringify(level.entities)},
${formatSlopes(level.slopes, level.cols)}  tiles: [
${formatTiles(level.tiles, level.cols)}
  ],
};
`;
}

mkdirSync(OUT_DIR, { recursive: true });

const sources = readdirSync(SRC_DIR).filter((f) => f.endsWith(".ldtk"));
if (sources.length === 0) {
  console.error("no .ldtk files in levels/");
  process.exit(1);
}

for (const source of sources) {
  const ldtk = JSON.parse(readFileSync(new URL(source, SRC_DIR), "utf8"));
  const level = convert(ldtk, source);
  const name = basename(source, ".ldtk");
  writeFileSync(new URL(`${name}.ts`, OUT_DIR), emit(level, source));
  const shaped = Object.keys(level.slopes).length;
  console.log(
    `${source} -> packages/engine/src/engine/levels/${name}.ts (${level.cols}x${level.rows}, ` +
      `${level.entities.length} entities, ${shaped} shaped slope tiles)`,
  );
}
